name: startup_analytics
version: "1.0.0"

profile: startup_analytics

model-paths: ["models"]
test-paths: ["tests"]
target-path: "target"
clean-targets: ["target", "dbt_packages", "logs"]

models:
  startup_analytics:
    staging:
      +materialized: view
    marts:
      +materialized: table
